// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkqbRGk0U-2RIqxAEp6ggUOUVPgLLA5u4',
    appId: '1:945290501334:web:652c9e65be3b3ef4a0bd77',
    messagingSenderId: '945290501334',
    projectId: 'chat-app-f631e',
    authDomain: 'chat-app-f631e.firebaseapp.com',
    storageBucket: 'chat-app-f631e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhm5oMaOXOtMgYIdMf1-OFvoV3n9aHu0M',
    appId: '1:945290501334:android:d905b5fb76baa225a0bd77',
    messagingSenderId: '945290501334',
    projectId: 'chat-app-f631e',
    storageBucket: 'chat-app-f631e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCcotPODd3yLziVpmOlJZh7nXylLk6-frY',
    appId: '1:945290501334:ios:682728cf0a27d335a0bd77',
    messagingSenderId: '945290501334',
    projectId: 'chat-app-f631e',
    storageBucket: 'chat-app-f631e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCcotPODd3yLziVpmOlJZh7nXylLk6-frY',
    appId: '1:945290501334:ios:682728cf0a27d335a0bd77',
    messagingSenderId: '945290501334',
    projectId: 'chat-app-f631e',
    storageBucket: 'chat-app-f631e.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAkqbRGk0U-2RIqxAEp6ggUOUVPgLLA5u4',
    appId: '1:945290501334:web:d6a91efc79831b36a0bd77',
    messagingSenderId: '945290501334',
    projectId: 'chat-app-f631e',
    authDomain: 'chat-app-f631e.firebaseapp.com',
    storageBucket: 'chat-app-f631e.appspot.com',
  );
}
